arch='RISC-V'
platform='UEFI'
drive_url='https://repo.openeuler.org/openEuler-25.09/virtual_machine_img/riscv64/openEuler-25.09-riscv64.qcow2.xz'
drive_type='qcow2'
compress_format='xz'
VIRT_CODE='https://repo.openeuler.org/openEuler-25.09/virtual_machine_img/riscv64/RISCV_VIRT_CODE.fd'
VIRT_VARS='https://repo.openeuler.org/openEuler-25.09/virtual_machine_img/riscv64/RISCV_VIRT_VARS.fd'
input_excel='/root/第一轮测试组筛选.xlsx'
from_to=[2,641]
